export const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Short",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStack: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "addidas fit short",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStack: 20,
      brand: "addidas",
      rating: 4,
      numReviews: 8,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacosto free Short",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStack: 0,
      brand: "Lacosto",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 80,
      countInStack: 15,
      brand: "Nike",
      rating: 4.8,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "puma Slim pant",
      category: "pant",
      image: "/images/p5.jpg",
      price: 130,
      countInStack: 5,
      brand: "puma",
      rating: 4.3,
      numReviews: 29,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "adidas Slim pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 120,
      countInStack: 12,
      brand: "adidas",
      rating: 4.6,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
